name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: |
          echo "RELEASE_NAME_SUFFIX=(Codename: $(cat CODENAME))" >> $GITHUB_ENV
      - name: Set Version
        run: |
          export RELEASE_VERSION=$(echo $GITHUB_REF | awk -F\/ '{print $3}')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Release Version is $RELEASE_VERSION" 
          echo "$RELEASE_VERSION" > VERSION
          if echo "${{ env.RELEASE_VERSION}}" | grep "rc" > /dev/null ; then
            echo "RELEASE_PRE=true" >> $GITHUB_ENV 
            echo "RELEASE_LATEST=false" >> $GITHUB_ENV 
          else
            echo "RELEASE_PRE=false" >> $GITHUB_ENV 
            echo "RELEASE_LATEST=true" >> $GITHUB_ENV 
          fi
      - name: Build Version
        run: |
          bash -c "chmod 755 .github/scripts/version.sh; .github/scripts/version.sh"
          bash -c "chmod 755 .github/scripts/readme.sh; .github/scripts/readme.sh"
          bash -c "chmod 755 .github/scripts/docs.sh; .github/scripts/docs.sh"
      - name: push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish'
          force-add: 'true'
          files:  README.md VERSION
          name: rsliotta
          email: bob@bobdot.me
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: "CHANGES.md"
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "${{ env.RELEASE_PRE }}"
          ALLOW_EMPTY_CHANGELOG: "false"
        with:
          args: |
            beeline.sh
